### ISSUE TITLE
Fail to get the correct Dataframe data from Json

### ISSUE THREAD

**Issue by wilson13349315** [nhcb/entsog-py#13]
Hi nhcb,

I run the scripts today and it returned with the key error message below:

File "<ipython-input-3-c327457962d9>", line 15, in <cell line: 15>
df = client.query_operational_data_all(start = start, end = end, indicators = ['physical_flow'])
df = pd.json_normalize(json_data[keys[1]])
IndexError: list index out of range

I think their original json format data had changed a little bit.

**Comment by nhcb** [comment]
Hi Wilson,

Thanks for notifying me, I missed these errors as well in my scripts. It seems like the original parse method in parsers.py doesn't work as intended.
```
def _extract_data(json_text):
    json_data = json.loads(json_text)

    keys = list(json_data.keys())
    df = pd.json_normalize(json_data[keys[1]])

    return df


def parse_general(json_text):
    df = _extract_data(json_text)
    df.columns = [to_snake_case(col) for col in df.columns]
    return df
def parse_operational_data(json_text: str, verbose: bool):
    data = parse_general(json_text)
    ...
```
The error is happening when it's unpacking the data in parse_operational_data. What the code essentially does is to get all the keys from the original JSON, and then selecting the second key (which is often the dataset's name).  This second key is then used to select the correct data from the JSON. 

What I believe is happening is that an error is slipping through when no data is returned by the server. It would give me an empty JSON back, or something similar, but no 2 keys, so that keys[1] may not be selected. Before, all errors were caught; however, ENTSOG might have changed something about their error handling. I will take a look at it tomorrow.

Also, may I ask what you are using the data for? I am glad some people are using the package :).

![image](https://user-images.githubusercontent.com/59085665/215974304-4c7645ba-54b8-4bc4-a81f-83ed0dcfbfb3.png)

**Comment by wilson13349315** [comment]
Hi nhcb,

I think your package is easy to use and I also planned to contribute your
package if I could.

For me, I work as an analyst and I will have a look at the Russian gas flow
into Europe weekly to see whether some major changes occurred for the past
week.

Thanks,
Wilson

**Comment by nhcb** [comment]
Hi Wilson,

It seems like they have added a response when there is no data available:
![image](https://user-images.githubusercontent.com/59085665/216595536-d33d83d0-decb-4492-9e4b-c2869833a8a4.png)
This broke the package. I have fixed it in the new version, I also noticed you could do HTTPS requests so I removed the `verify=False`.

I will launch it tonight.
