### ISSUE TITLE
tests.py unupdated?

### ISSUE THREAD

**Issue by r-uben** [nhcb/entsog-py#2]
Hi,

I'm trying to use your code (thanks a lot for having it public) to download some data and I'm reading the tests.py file. However, I think there are some things that are not yet updated or nor working. First, when using query_interruptions, there are not "country_code", "start"; "end" inputs anymore, right? Second, when using the small loop to aggregate data (lines 64-78), you don't include the balancing_zone, why?

Sorry to bother you and thanks a lot for your work.

Best,
R

**Comment by nhcb** [comment]
Hey! Thanks for using the package. It's defenitely a work in progress and the tests.py is a very old version of me querying the data to see whether some stuff works. I'll try and update it soon as the API calls are somewhat correct now. 

Regarding query_interruptions, I believe countryCode wasn't a valid parameter on the ENTSOG side. Hence, I query all data instead; since for me I just wanted European data anyway. 

I recommend that instead of using the query_aggregated_data, you run the function query_operational_data_all, it will download all European data day-by-day. But afterwards you can just select what you need from it. Currently, this is the fastest way to download the correct data. I noticed that on ENTSOG side the aggregate data (query_aggregate_data) is full of duplicates and weird combinations of gas points.

**Comment by r-uben** [comment]
Thank you very much! Very useful (and sorry for the late answer).
